require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::StoreOwnersController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::StoreOwner. As you add validations to Admin::StoreOwner, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::StoreOwnersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all admin_store_owners as @admin_store_owners" do
      store_owner = Admin::StoreOwner.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_store_owners).should eq([store_owner])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_store_owner as @admin_store_owner" do
      store_owner = Admin::StoreOwner.create! valid_attributes
      get :show, {:id => store_owner.to_param}, valid_session
      assigns(:admin_store_owner).should eq(store_owner)
    end
  end

  describe "GET new" do
    it "assigns a new admin_store_owner as @admin_store_owner" do
      get :new, {}, valid_session
      assigns(:admin_store_owner).should be_a_new(Admin::StoreOwner)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_store_owner as @admin_store_owner" do
      store_owner = Admin::StoreOwner.create! valid_attributes
      get :edit, {:id => store_owner.to_param}, valid_session
      assigns(:admin_store_owner).should eq(store_owner)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::StoreOwner" do
        expect {
          post :create, {:admin_store_owner => valid_attributes}, valid_session
        }.to change(Admin::StoreOwner, :count).by(1)
      end

      it "assigns a newly created admin_store_owner as @admin_store_owner" do
        post :create, {:admin_store_owner => valid_attributes}, valid_session
        assigns(:admin_store_owner).should be_a(Admin::StoreOwner)
        assigns(:admin_store_owner).should be_persisted
      end

      it "redirects to the created admin_store_owner" do
        post :create, {:admin_store_owner => valid_attributes}, valid_session
        response.should redirect_to(Admin::StoreOwner.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_store_owner as @admin_store_owner" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::StoreOwner.any_instance.stub(:save).and_return(false)
        post :create, {:admin_store_owner => { "name" => "invalid value" }}, valid_session
        assigns(:admin_store_owner).should be_a_new(Admin::StoreOwner)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::StoreOwner.any_instance.stub(:save).and_return(false)
        post :create, {:admin_store_owner => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_store_owner" do
        store_owner = Admin::StoreOwner.create! valid_attributes
        # Assuming there are no other admin_store_owners in the database, this
        # specifies that the Admin::StoreOwner created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::StoreOwner.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => store_owner.to_param, :admin_store_owner => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested admin_store_owner as @admin_store_owner" do
        store_owner = Admin::StoreOwner.create! valid_attributes
        put :update, {:id => store_owner.to_param, :admin_store_owner => valid_attributes}, valid_session
        assigns(:admin_store_owner).should eq(store_owner)
      end

      it "redirects to the admin_store_owner" do
        store_owner = Admin::StoreOwner.create! valid_attributes
        put :update, {:id => store_owner.to_param, :admin_store_owner => valid_attributes}, valid_session
        response.should redirect_to(store_owner)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_store_owner as @admin_store_owner" do
        store_owner = Admin::StoreOwner.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::StoreOwner.any_instance.stub(:save).and_return(false)
        put :update, {:id => store_owner.to_param, :admin_store_owner => { "name" => "invalid value" }}, valid_session
        assigns(:admin_store_owner).should eq(store_owner)
      end

      it "re-renders the 'edit' template" do
        store_owner = Admin::StoreOwner.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::StoreOwner.any_instance.stub(:save).and_return(false)
        put :update, {:id => store_owner.to_param, :admin_store_owner => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_store_owner" do
      store_owner = Admin::StoreOwner.create! valid_attributes
      expect {
        delete :destroy, {:id => store_owner.to_param}, valid_session
      }.to change(Admin::StoreOwner, :count).by(-1)
    end

    it "redirects to the admin_store_owners list" do
      store_owner = Admin::StoreOwner.create! valid_attributes
      delete :destroy, {:id => store_owner.to_param}, valid_session
      response.should redirect_to(admin_store_owners_url)
    end
  end

end
