require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ImeisController do

  # This should return the minimal set of attributes required to create a valid
  # Imei. As you add validations to Imei, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "imei_num" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ImeisController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all imeis as @imeis" do
      imei = Imei.create! valid_attributes
      get :index, {}, valid_session
      assigns(:imeis).should eq([imei])
    end
  end

  describe "GET show" do
    it "assigns the requested imei as @imei" do
      imei = Imei.create! valid_attributes
      get :show, {:id => imei.to_param}, valid_session
      assigns(:imei).should eq(imei)
    end
  end

  describe "GET new" do
    it "assigns a new imei as @imei" do
      get :new, {}, valid_session
      assigns(:imei).should be_a_new(Imei)
    end
  end

  describe "GET edit" do
    it "assigns the requested imei as @imei" do
      imei = Imei.create! valid_attributes
      get :edit, {:id => imei.to_param}, valid_session
      assigns(:imei).should eq(imei)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Imei" do
        expect {
          post :create, {:imei => valid_attributes}, valid_session
        }.to change(Imei, :count).by(1)
      end

      it "assigns a newly created imei as @imei" do
        post :create, {:imei => valid_attributes}, valid_session
        assigns(:imei).should be_a(Imei)
        assigns(:imei).should be_persisted
      end

      it "redirects to the created imei" do
        post :create, {:imei => valid_attributes}, valid_session
        response.should redirect_to(Imei.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved imei as @imei" do
        # Trigger the behavior that occurs when invalid params are submitted
        Imei.any_instance.stub(:save).and_return(false)
        post :create, {:imei => { "imei_num" => "invalid value" }}, valid_session
        assigns(:imei).should be_a_new(Imei)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Imei.any_instance.stub(:save).and_return(false)
        post :create, {:imei => { "imei_num" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested imei" do
        imei = Imei.create! valid_attributes
        # Assuming there are no other imeis in the database, this
        # specifies that the Imei created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Imei.any_instance.should_receive(:update).with({ "imei_num" => "MyString" })
        put :update, {:id => imei.to_param, :imei => { "imei_num" => "MyString" }}, valid_session
      end

      it "assigns the requested imei as @imei" do
        imei = Imei.create! valid_attributes
        put :update, {:id => imei.to_param, :imei => valid_attributes}, valid_session
        assigns(:imei).should eq(imei)
      end

      it "redirects to the imei" do
        imei = Imei.create! valid_attributes
        put :update, {:id => imei.to_param, :imei => valid_attributes}, valid_session
        response.should redirect_to(imei)
      end
    end

    describe "with invalid params" do
      it "assigns the imei as @imei" do
        imei = Imei.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Imei.any_instance.stub(:save).and_return(false)
        put :update, {:id => imei.to_param, :imei => { "imei_num" => "invalid value" }}, valid_session
        assigns(:imei).should eq(imei)
      end

      it "re-renders the 'edit' template" do
        imei = Imei.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Imei.any_instance.stub(:save).and_return(false)
        put :update, {:id => imei.to_param, :imei => { "imei_num" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested imei" do
      imei = Imei.create! valid_attributes
      expect {
        delete :destroy, {:id => imei.to_param}, valid_session
      }.to change(Imei, :count).by(-1)
    end

    it "redirects to the imeis list" do
      imei = Imei.create! valid_attributes
      delete :destroy, {:id => imei.to_param}, valid_session
      response.should redirect_to(imeis_url)
    end
  end

end
